
application:
  admin:
    kaptcha-open: false             #是否开启登录时验证码 (true/false)
    spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
    session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
    session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  message:
    captch.template: SMS_150742325

spring:
  profiles:
    active: @spring.active@
  messages:
    always-use-message-format: true
    basename: i18n/messages
    cache-seconds: 60
    encoding: UTF-8
    fallback-to-system-locale: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.stylefeng.guns.modular.system.model
  mapperLocations: classpath*:mapper/*.xml

---

server:
  port: 8080
  servlet:
    context-path: /admin
  tomcat:
    max-connections: 100
    uri-encoding: UTF-8
    accept-count: 75
    max-threads: 100

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kcdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: kcapp
    password: h,M)Hww0,.rz
    db-name: kcdb #用来搜集数据库的所有表
    filters: wall,mergeStat
application:
  attachment:
    visit-url: http://127.0.0.1:8080/admin/attachment/download
    store-path: /Users/huahua/Workbase/data/gs/upload

---

server:
  port: 18001
  servlet:
    context-path: /admin
  tomcat:
    max-connections: 1024
    uri-encoding: UTF-8
    accept-count: 768
    max-threads: 1024

spring:
  profiles: produce
  datasource:
    jdbcUrl: jdbc:mysql://172.26.140.96:33009/kcdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: kcapp
    password: h,M)Hww0,.rz
    db-name: kcdb #用来搜集数据库的所有表
    filters: wall,mergeStat
application:
  attachment:
    visit-url: http://www.kecui.com.cn/download
    store-path: /home/app/data/upload
